# -*- coding: utf-8 -*-
"""CR-Task-2-Python-Intern-Anand-Yadav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjJvCOXDABj7YpHzF1fUlLBnkmHKgRnp

# **Budget Tracker using Python**
"""

import csv
import os

# File to store transactions
file_path = 'budget_tracker.csv'

# Function to initialize the CSV file
def initialize_file():
    if not os.path.exists(file_path):
        with open(file_path, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Type", "Category", "Amount"])

# Function to add a transaction
def add_transaction(transaction_type, category, amount):
    with open(file_path, 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([transaction_type, category, amount])

# Function to calculate budget
def calculate_budget():
    total_income = 0
    total_expense = 0
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        for row in reader:
            if row[0] == 'Income':
                total_income += float(row[2])
            elif row[0] == 'Expense':
                total_expense += float(row[2])
    return total_income, total_expense, total_income - total_expense

# Function to categorize expenses
def categorize_expenses():
    categories = {}
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        for row in reader:
            if row[0] == 'Expense':
                if row[1] in categories:
                    categories[row[1]] += float(row[2])
                else:
                    categories[row[1]] = float(row[2])
    return categories

# Main function
def main():
    initialize_file()
    while True:
        print("\nPersonal Budget Tracker")
        print("1. Add Income")
        print("2. Add Expense")
        print("3. View Budget")
        print("4. View Expense Analysis")
        print("5. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            category = input("Enter income category: ")
            amount = float(input("Enter amount: "))
            add_transaction('Income', category, amount)
        elif choice == '2':
            category = input("Enter expense category: ")
            amount = float(input("Enter amount: "))
            add_transaction('Expense', category, amount)
        elif choice == '3':
            total_income, total_expense, remaining_budget = calculate_budget()
            print(f"\nTotal Income: {total_income}")
            print(f"Total Expense: {total_expense}")
            print(f"Remaining Budget: {remaining_budget}")
        elif choice == '4':
            categories = categorize_expenses()
            print("\nExpense Analysis by Category:")
            for category, amount in categories.items():
                print(f"{category}: {amount}")
        elif choice == '5':
            print("Exiting Personal Budget Tracker. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()